# Generated by Django 3.0.6 on 2020-06-02 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marystuffs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
    ]
