# Generated by Django 3.0.6 on 2020-06-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marystuffs', '0003_auto_20200606_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='last',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
